apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu-pod
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: charts/ubuntu-pod
    repoURL: https://github.com/hellebore74/helm-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      